codecov:
  allow_pseudo_compare: True

coverage:
  status:
    project:
      default:
        flags:
          - app_a
          - app_b

comment:
  require_base: no
  layout: " diff, flags, files"
  require_changes: false


flags:
  app_a:
    carryforward: true
  app_b:
    carryforward: true
