codecov:
  allow_pseudo_compare: True

coverage:
  status:
    project:
      default:
        flags:
          - app_a
          - app_b

comment:
  layout: " diff, flags, files"

flags:
  app_a:
    carryforward: true
  app_b:
    carryforward: true
